### PR TITLE
Posting iPython Notebooks with data analysis

### PR DESCRIPTION
**Pull request by piafaustino**

### CODE REVIEW

**Comment by stefsy** [comment]
Lgtm

**Comment by piafaustino** [comment]
@stefsy, @antoniocarlosortiz and I both were like "What's LGTM." Google told us it means "Let's Get This Money." ?? haha

**Comment by benigeri** [comment]
looks good to me lol

—
Paul Benigeri
Co-founder, Backslash
http://backslash.io

**Comment by stefsy** [comment]
I like Let's get this money hahaha!
"Looks good to me" ;)

**Pull request merged**
